# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
pod 'AFNetworking'
pod 'JSONKit-NoWarning'
pod 'SMPageControl'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'RatingBar'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'UMengAnalytics-NO-IDFA'
pod 'NSLogger'
pod 'SDiPhoneVersion'
